[2022-04-26 16:24:22,137 leo1311_main.py line:70] INFO HTTPConnectionPool(host='10.3.2.40', port=30083): Max retries exceeded with url: /answer/submit (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe836d48be0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
[2022-04-26 16:24:22,140 web.py line:2239] INFO 200 GET /algo-server (::1) 75360.07ms
